# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annotatorwidget.ui'
#
# Created: Tue May 28 13:11:55 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AnnotatorWidget(object):
    def setupUi(self, AnnotatorWidget, shared_open_gl_widget):
        AnnotatorWidget.setObjectName("AnnotatorWidget")
        AnnotatorWidget.resize(1080, 740)
        self.horizontalLayout = QtGui.QHBoxLayout(AnnotatorWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlPanel_groupBox = QtGui.QGroupBox(AnnotatorWidget)
        self.controlPanel_groupBox.setObjectName("controlPanel_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.controlPanel_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.time_groupBox.setObjectName("time_groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.time_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timeValue_label = QtGui.QLabel(self.time_groupBox)
        self.timeValue_label.setObjectName("timeValue_label")
        self.gridLayout_4.addWidget(self.timeValue_label, 0, 0, 1, 1)
        self.timeValue_doubleSpinBox = QtGui.QDoubleSpinBox(self.time_groupBox)
        self.timeValue_doubleSpinBox.setMaximum(12000.0)
        self.timeValue_doubleSpinBox.setObjectName("timeValue_doubleSpinBox")
        self.gridLayout_4.addWidget(self.timeValue_doubleSpinBox, 0, 1, 1, 1)
        self.timePlayStop_pushButton = QtGui.QPushButton(self.time_groupBox)
        self.timePlayStop_pushButton.setObjectName("timePlayStop_pushButton")
        self.gridLayout_4.addWidget(self.timePlayStop_pushButton, 1, 1, 1, 1)
        self.timeLoop_checkBox = QtGui.QCheckBox(self.time_groupBox)
        self.timeLoop_checkBox.setObjectName("timeLoop_checkBox")
        self.gridLayout_4.addWidget(self.timeLoop_checkBox, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.time_groupBox)
        self.tracking_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.tracking_groupBox.setObjectName("tracking_groupBox")
        self.gridLayout = QtGui.QGridLayout(self.tracking_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtGui.QProgressBar(self.tracking_groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 7, 0, 1, 2)
        self.frameLabel = QtGui.QLabel(self.tracking_groupBox)
        self.frameLabel.setObjectName("frameLabel")
        self.gridLayout.addWidget(self.frameLabel, 0, 0, 1, 1)
        self.previousFrame_pushButton = QtGui.QPushButton(self.tracking_groupBox)
        self.previousFrame_pushButton.setObjectName("previousFrame_pushButton")
        self.gridLayout.addWidget(self.previousFrame_pushButton, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.nextFrame_pushButton = QtGui.QPushButton(self.tracking_groupBox)
        self.nextFrame_pushButton.setObjectName("nextFrame_pushButton")
        self.gridLayout.addWidget(self.nextFrame_pushButton, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tracking_groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 2)
        self.FrameMultiplier = QtGui.QSpinBox(self.tracking_groupBox)
        self.FrameMultiplier.setMinimum(1)
        self.FrameMultiplier.setMaximum(1000)
        self.FrameMultiplier.setProperty("value", 1)
        self.FrameMultiplier.setObjectName("FrameMultiplier")
        self.gridLayout.addWidget(self.FrameMultiplier, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.tracking_groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tracking_groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.reset_pushButton = QtGui.QPushButton(self.tracking_groupBox)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.gridLayout.addWidget(self.reset_pushButton, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.tracking_groupBox)
        self.cloudUpdate = QtGui.QPushButton(self.controlPanel_groupBox)
        self.cloudUpdate.setObjectName("cloudUpdate")
        self.verticalLayout.addWidget(self.cloudUpdate)
        self.modifcationsAllowed = QtGui.QCheckBox(self.controlPanel_groupBox)
        self.modifcationsAllowed.setObjectName("modifcationsAllowed")
        self.verticalLayout.addWidget(self.modifcationsAllowed)
        self.frame_2 = QtGui.QFrame(self.controlPanel_groupBox)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.plotProgress = QtGui.QPushButton(self.frame_2)
        self.plotProgress.setObjectName("plotProgress")
        self.horizontalLayout_6.addWidget(self.plotProgress)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.controlPanel_groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.done_pushButton = QtGui.QPushButton(self.frame)
        self.done_pushButton.setObjectName("done_pushButton")
        self.horizontalLayout_2.addWidget(self.done_pushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.controlPanel_groupBox)
        self.sceneviewer_widget = BaseSceneviewerWidget(AnnotatorWidget, shared_open_gl_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(AnnotatorWidget)
        QtCore.QMetaObject.connectSlotsByName(AnnotatorWidget)

    def retranslateUi(self, AnnotatorWidget):
        AnnotatorWidget.setWindowTitle(QtGui.QApplication.translate("AnnotatorWidget", "Image Based Fiducial Markers", None, QtGui.QApplication.UnicodeUTF8))
        self.controlPanel_groupBox.setTitle(QtGui.QApplication.translate("AnnotatorWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.time_groupBox.setTitle(QtGui.QApplication.translate("AnnotatorWidget", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.timeValue_label.setText(QtGui.QApplication.translate("AnnotatorWidget", "Time value:", None, QtGui.QApplication.UnicodeUTF8))
        self.timePlayStop_pushButton.setText(QtGui.QApplication.translate("AnnotatorWidget", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLoop_checkBox.setText(QtGui.QApplication.translate("AnnotatorWidget", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.tracking_groupBox.setTitle(QtGui.QApplication.translate("AnnotatorWidget", "Navigation:", None, QtGui.QApplication.UnicodeUTF8))
        self.frameLabel.setText(QtGui.QApplication.translate("AnnotatorWidget", "Current Frame number: ", None, QtGui.QApplication.UnicodeUTF8))
        self.previousFrame_pushButton.setText(QtGui.QApplication.translate("AnnotatorWidget", "Previous Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.nextFrame_pushButton.setText(QtGui.QApplication.translate("AnnotatorWidget", "Next Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AnnotatorWidget", "Amount completed at current rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AnnotatorWidget", "Multiply above buttons by", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AnnotatorWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_pushButton.setText(QtGui.QApplication.translate("AnnotatorWidget", "Reset current Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.cloudUpdate.setText(QtGui.QApplication.translate("AnnotatorWidget", "Sync with Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.modifcationsAllowed.setText(QtGui.QApplication.translate("AnnotatorWidget", "Allow Database Modifications when syncing", None, QtGui.QApplication.UnicodeUTF8))
        self.plotProgress.setText(QtGui.QApplication.translate("AnnotatorWidget", "Plot completed frames histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.done_pushButton.setText(QtGui.QApplication.translate("AnnotatorWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
