# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\imagebasedfiducialmarkerswidget.ui'
#
# Created: Sun Dec  2 13:56:20 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ImageBasedFiducialMarkersWidget(object):
    def setupUi(self, shared_open_gl_context, ImageBasedFiducialMarkersWidget):
        ImageBasedFiducialMarkersWidget.setObjectName("ImageBasedFiducialMarkersWidget")
        ImageBasedFiducialMarkersWidget.resize(870, 576)
        self.horizontalLayout = QtGui.QHBoxLayout(ImageBasedFiducialMarkersWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlPanel_groupBox = QtGui.QGroupBox(ImageBasedFiducialMarkersWidget)
        self.controlPanel_groupBox.setObjectName("controlPanel_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.controlPanel_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.time_groupBox.setObjectName("time_groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.time_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timePlayStop_pushButton = QtGui.QPushButton(self.time_groupBox)
        self.timePlayStop_pushButton.setObjectName("timePlayStop_pushButton")
        self.gridLayout_4.addWidget(self.timePlayStop_pushButton, 1, 1, 1, 1)
        self.timeValue_label = QtGui.QLabel(self.time_groupBox)
        self.timeValue_label.setObjectName("timeValue_label")
        self.gridLayout_4.addWidget(self.timeValue_label, 0, 0, 1, 1)
        self.timeValue_doubleSpinBox = QtGui.QDoubleSpinBox(self.time_groupBox)
        self.timeValue_doubleSpinBox.setMaximum(12000.0)
        self.timeValue_doubleSpinBox.setObjectName("timeValue_doubleSpinBox")
        self.gridLayout_4.addWidget(self.timeValue_doubleSpinBox, 0, 1, 1, 1)
        self.timeLoop_checkBox = QtGui.QCheckBox(self.time_groupBox)
        self.timeLoop_checkBox.setObjectName("timeLoop_checkBox")
        self.gridLayout_4.addWidget(self.timeLoop_checkBox, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.time_groupBox)
        self.tracking_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.tracking_groupBox.setObjectName("tracking_groupBox")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tracking_groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.track_pushButton = QtGui.QPushButton(self.tracking_groupBox)
        self.track_pushButton.setObjectName("track_pushButton")
        self.horizontalLayout_5.addWidget(self.track_pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addWidget(self.tracking_groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.statusText_label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusText_label.sizePolicy().hasHeightForWidth())
        self.statusText_label.setSizePolicy(sizePolicy)
        self.statusText_label.setObjectName("statusText_label")
        self.horizontalLayout_3.addWidget(self.statusText_label)
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(self.controlPanel_groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.done_pushButton = QtGui.QPushButton(self.frame)
        self.done_pushButton.setObjectName("done_pushButton")
        self.horizontalLayout_2.addWidget(self.done_pushButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.controlPanel_groupBox)
        self.sceneviewer_widget = BaseSceneviewerWidget(ImageBasedFiducialMarkersWidget, shared_open_gl_context)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(ImageBasedFiducialMarkersWidget)
        QtCore.QMetaObject.connectSlotsByName(ImageBasedFiducialMarkersWidget)

    def retranslateUi(self, ImageBasedFiducialMarkersWidget):
        ImageBasedFiducialMarkersWidget.setWindowTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Image Based Fiducial Markers", None, QtGui.QApplication.UnicodeUTF8))
        self.controlPanel_groupBox.setTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.time_groupBox.setTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.timePlayStop_pushButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.timeValue_label.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Time value:", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLoop_checkBox.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.tracking_groupBox.setTitle(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Tracking:", None, QtGui.QApplication.UnicodeUTF8))
        self.track_pushButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.statusText_label.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.done_pushButton.setText(QtGui.QApplication.translate("ImageBasedFiducialMarkersWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
